# Generated by Django 3.2.5 on 2021-10-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('height', models.CharField(max_length=200)),
                ('mass', models.CharField(max_length=200)),
                ('hair_color', models.CharField(max_length=200)),
                ('skin_color', models.CharField(max_length=200)),
                ('eye_color', models.CharField(max_length=200)),
                ('birth_year', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('homeworld', models.CharField(default='non', max_length=200)),
            ],
        ),
    ]
